version: "3"
services:
  container1:
    container_name: compute_app
    build: ./container1
    volumes:
      - .:/data
    ports:
      - "6000:6000"

  container2:
    container_name: gatekeeper_app
    build: ./container2
    volumes:
      - .:/data
    expose:
      - "8000"


